schema_version = "1.0.0"

blender_version_min = "4.2.0"
id = "StoryboardHelper"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "Niceboat Animation、小萌新、JuanZhi、只剩一瓶辣椒酱"
name = "Storyboard Helper"
tagline = "Storyboard Helper"
type = "add-on"
version = "1.0.5"
tags = ["3D View", "Modeling", "Mesh", "Object"]
