data = {
    "Add Timeline Marker": "添加时间线标记",
    "Delete Timeline Marker": "删除时间线标记",
    "Rename Timeline Markers": "重命名时间线标记",
    "Deleted timeline marker %s": "删除时间线标记 %s",
    "Timeline markers are not match %s": "时间线标记未匹配 %s",
    "Storyboard": "故事板",
    "Timeline Marker": "时间线标记",
    "Render Storyboard": "渲染故事板",
    "Ctrl: Directly render without previewing": "Ctrl :直接渲染，不预览",
    "Time stamp not found": "未找到时间戳",
    "No frames found for rendering": "未找到需要渲染的帧",

    "Scale F Curves": "缩放F曲线",
    "Designate Scale Range": "指定缩放范围",
    "Move Frame Range": "移动帧范围",
    "Scale Frame Range": "缩放帧范围",
    "Move Frame to": "移动帧到",
    "Scale Factor": "缩放系数",
    "Scaling completed with %s frames deleted": "缩放完成 有%s帧被删除",
    "There is an error in the specified frame range": "指定的帧范围出现错误",

    "Render Out": "渲染输出",
    "Panel Name": "面板名称",
    "Sync Timeline Markers Frame": "同步时间线标记帧",
    "Sync Timeline Markers Select": "同步时间线标记选择",

    "Prefix": "前缀",
    "Suffix": "后缀",
    "Int Size": "整数大小",
    "Preview": "预览",
    "Preview Count": "预览数量",

    "Capture Delay": "捕获延迟",
    "How much time to wait (seconds) before capturing each frame, to allow the viewport to clean up": "在捕获每一帧之前等待多长时间（秒），以允许视口清理",
    "Out File Format": "输出文件格式",
    "The file output path is incorrect, please check!!": "文件输出路径错误,请检查!!",
    "Replace": "替换",
    "Select Replace": "选择替换",
    "Render complete": "渲染完成",

    "Tips: Some attributes will only change during rendering": "Tips: 部分属性在渲染时才会改变",
    "Folder split by \\": "文件夹需要以\\拆分",
    "Cancel rendering": "取消渲染",

    "By Frame": "按帧",
    "By Storyboard": "按故事板",
    "By Timelines markers": "按时间线标记",
    "Folder for rendering output":"渲染输出的文件夹",
    "Scene name":"场景名称",
    "View layer name":"视图层名称",
    "Frame int 1,2":"整数帧 1,2",
    "Fill 1 -> 0001,2 -> 0002":"填充 1 -> 0001,2 -> 0002",
    "Output file suffix":"输出文件后缀",
    "Current camera name":"当前相机名称",

    "Timelines markers":"时间线标记",
    "All frame":"所有帧",
}
